services:
  python:
    build: .
    env_file:
      - .env
    command: sleep infinity
    volumes:
      - .:/app:cached

  db:
    image: timescale/timescaledb:2.17.2-pg16
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
